include "baseconfig.conf"

kafka {
  input.topic = "transform"
  output.system.event.topic = "system.events"
  output.failed.topic = "summary.failed"
  output.summary.topic = "summary"
  output.summary.failed.topic = "failed"
  groupId = "summarizer-group"
}

task {
  consumer.parallelism = 1
  downstream.operators.parallelism = 1
}

// in seconds
idleTime = 10 * 60
sessionBreakTime = 30 * 60
waterMarkTimeBound = 5
