include "baseconfig.conf"

kafka {
  input.topic = "transform"
  output.summary.topic = "summary"
  output.summary.failed.topic = "failed"
  groupId = "summarizer-group"
}

task {
  consumer.parallelism = 1
  downstream.operators.parallelism = 1
}