name: Pull Request
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test-cases:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
            java-version: 11

      - name: Maven Build
        run: |
          mvn clean test

#run-name: Workflow run for pull request - ${{ github.event.pull_request.title }}